apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: prisoner-dilemma-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: strategy_type
      value: "titfortat"  # Options: random, titfortat, always_cooperate, always_defect
    - name: cooperate_prob
      value: "0.5"        # Determines how often a "random" strategy cooperates (1.0 = always, 0.0 = never)

  templates:
  - name: main
    dag:
      tasks:
      - name: train-model
        template: train-model
        arguments:
          parameters:
          - name: strategy_type
            value: "{{workflow.parameters.strategy_type}}"
          - name: cooperate_prob
            value: "{{workflow.parameters.cooperate_prob}}"
      
      - name: evaluate-model
        template: evaluate-model
        depends: train-model
        arguments:
          parameters:
          - name: strategy_type
            value: "{{workflow.parameters.strategy_type}}"
          - name: cooperate_prob
            value: "{{workflow.parameters.cooperate_prob}}"
          artifacts:
          - name: q-table
            from: "{{tasks.train-model.outputs.artifacts.q-table}}"

  - name: train-model
    inputs:
      parameters:
      - name: strategy_type
      - name: cooperate_prob
    outputs:
      artifacts:
      - name: q-table
        path: /tmp/qtable.pkl
    container:
      image: danielboothcloud/prisoners-dilemma:v1.1
      imagePullPolicy: Always
      command: [python, "/app/train.py"]
      args: [
        "--strategy_type", "{{inputs.parameters.strategy_type}}",
        "--cooperate_prob", "{{inputs.parameters.cooperate_prob}}",
        "--output", "/tmp/qtable.pkl"
      ]

  - name: evaluate-model
    inputs:
      parameters:
      - name: strategy_type
      - name: cooperate_prob
      artifacts:
      - name: q-table
        path: /tmp/qtable.pkl
    outputs: 
      artifacts:
      - name: results
        path: /app/evaluation_report.txt
        archive:
          none: {} 
    container:
      image: danielboothcloud/prisoners-dilemma:v1.1
      imagePullPolicy: Always
      command: [python, "/app/evaluate.py"]
      args: [
        "--strategy_type", "{{inputs.parameters.strategy_type}}",
        "--cooperate_prob", "{{inputs.parameters.cooperate_prob}}",
        "--q_table", "/tmp/qtable.pkl"
      ]